#!perl
use v5.30.0;
use warnings;

use lib 'lib';
use Wink;
use Wink::Program;

my $bank = Wink->get_bank;

my $program = $bank->build_program([
  [ set   => { device => 'left',  rgb => 'ff0000' } ],
  [ sleep => { time   => 250 } ],
  [ set   => { device => 'right', rgb => 'ff0000' } ],
  [ sleep => { time   => 250 } ],
  [ set   => { device => 'mid',   rgb => 'ff0000' } ],
  [ sleep => { time   => 250 } ],
]);

$program->execute;
