#!perl
use v5.30.0;
use warnings;

use lib 'lib';
use Wink;

my $wink = Wink->new({ device => '/dev/hidraw0' });

$wink->fadeto('ff0000');
sleep 1;

$wink->fadeto('00ff00', 1);
sleep 1;

$wink->fadeto('0000ff', 2);
sleep 1;

$wink->fadeto('ffffff');
sleep 2;

$wink->off;

