#!/usr/bin/env perl
use v5.36.0;

use Getopt::Long::Descriptive;

my ($opt, $usage) = describe_options(
  '%c %o',
  [ 'sn=s@', 'serial numbers, in order, to mount as device 0..n' ],
);

unless ($opt->sn && $opt->sn->@*) {
  die "You didn't specify any serial numbers with --sn, so nothing to do!\n";
}

my @serials = $opt->sn->@*;

my @paths = map {; "/dev/blink/$_" } @serials;

my @missing = grep {; ! -e } @paths;

if (@missing) {
  my $error = "Devices for some requested serial numbers not found:\n";
  $error .= "- $_\n" for @missing;
  die $error;
}

my $bank = join q{,},
           map {; "$_:hidraw:$paths[$_]" } keys @paths;

say $bank;
